### ISSUE TITLE
Member 엔드포인트 구현

### ISSUE THREAD

**Issue by worjs** [kuaaa-telecom/server.kuaaa.net#10]
## Description
- Auth가 아닌, member 명부에 대한 CRUD를 구현합니다.

## Todo
- [x] C, U, D를 구현합니다.
- [ ] R을 구현합니다(확정 x)
- [ ] 관리자 권한의 업데이트는 특정 계정의 권한 변경이 가능해야 합니다.
- [ ] 일반 유저가 자신의 정보를 확인할 수 있어야 합니다.(nickname 포함)
- [ ] 일반 유저가 자신의 정보를 수정할 수 있어야 합니다.(비밀번호는 안됨)
