### ISSUE TITLE
DB & ORM 세팅

### ISSUE THREAD

**Issue by worjs** [kuaaa-telecom/server.kuaaa.net#3]
## Todo
- [x] Prisma 세팅, 로컬에서 간단한 스키마 넣고 테스트
- [x] 스키마 작성
- [x] local db로 migration
- [ ] dev db로 migration
